### ISSUE TITLE
Version Flag

### ISSUE THREAD

**Issue by zQueal** [codesoap/atto#1]
Without rebuilding, it's difficult to tell if/that you have the newest version available. Could fix it with a `--version` flag.

**Comment by codesoap** [comment]
Sounds like a reasonable addition. Implemented in https://github.com/codesoap/atto/commit/a27428c7924e89198a27c41b95f3f7730d124822 and released at https://github.com/codesoap/atto/releases/tag/v1.2.0. To be consistent with the existing `-h`, `-a` and `-y` flags I have chosen to go with `-v` instead of `--version`.

Thanks for your feedback!
