### ISSUE TITLE
[Feature Request] doRPC Basic Auth

### ISSUE THREAD

**Issue by Gigaion** [codesoap/atto#10]
I am still new to Golang, although I was able to verify that atto is compatiable with using BasicAuth.
BasicAuth is useful when your specified node is using NanoRPCProxy along with basic authentication.

I will open this issue request in the unlikely event I am unable to modify the source code in a way that is Pull Request worthy.

**Example modified code (var is specified in function, but needs to be moved to config.go):**
```
func doRPC(requestBody, node string) (responseBytes []byte, err error) {
	//resp, err := http.Post(node, "application/json", strings.NewReader(requestBody))
	client := &http.Client{}
	req, err := http.NewRequest("POST", node, strings.NewReader(requestBody))
	req.Header.Set("Content-Type", "application/json")
	
	var nodeBasicAuth = "exampleUsername1:examplePassword1"
	if nodeBasicAuth != "" {
		nodeBasicAuthSplit := strings.Split(nodeBasicAuth, ":")
		if len(nodeBasicAuthSplit) >= 2 {
			if nodeBasicAuthSplit[0] != "" && nodeBasicAuthSplit[1] != "" {
				req.SetBasicAuth(nodeBasicAuthSplit[0], nodeBasicAuthSplit[1])
			}
		}
	}
	
	resp, err := client.Do(req)
	if err != nil {
		return
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		err = fmt.Errorf("received unexpected HTTP return code %d", resp.StatusCode)
		return
	}
	return ioutil.ReadAll(resp.Body)
}
```

**The eventual goal is to be able to specify "nodeBasicAuth" in the config,go:**
```
var (
       --SNIP--

	//If RPC uses Basic Auth (leave blank if none). Use format: "Username:Password"
	//nodeBasicAuth = ""
	nodeBasicAuth = "exampleUsername1:examplePassword1"
```

**Comment by codesoap** [comment]
I don't understand why you want to do this. I cannot find any RPC authentication config on docs.nano.org. What is your use case?

**Comment by Gigaion** [comment]
> I don't understand why you want to do this. I cannot find any RPC authentication config on docs.nano.org. What is your use case?

This is an authentication feature of the popular NanoRPCProxy (used by most publicly available nano nodes): https://github.com/Joohansson/NanoRPCProxy

If you don't want to publicly allow people to do RPC commands on your node, you can specify a username/password the RPC api.

This is useful if your node's RPC proxy is public.

**Comment by zQueal** [comment]
Pretty sure this is outside the scope of what codesoap wants to do with atto, but it's a pretty great feature. I've stopped using atto because I can't use my private node, which requires auth to be able to execute certain commands. By adding this feature I would be able to make requests that comply with basic auth for protected endpoints.

I wouldn't have to sacrifice security (opening my node to the world) to be able to use atto again.

I think it's worth seriously considering adding. Adding username/password variables to the `config.go` before compiling would be a great way to do this. Just my $0.02.

**Comment by codesoap** [comment]
I think being able to use private nodes is a good feature. Since @Gigaion closed this issue by himself, I assumed he didn't need the feature anymore, so I didn't implement anything.

The one thing that makes me a little hesitant is, that the authentication is not part of the official node implementation, but of a third party proxy, but if it is true, that the proxy of @Joohhansson is by far the most popular, I would be OK with implementing it's authentication procedure.

I have implemented a first version of this feature on a branch. Could you try it and tell me if it works, @zQueal (I don't have a private node which I could use to test this)? Here is how you can test it; note that environment variables are used instead of a variable in `config.go`, since I consider this more secure:
```console
$ cd ~/path/to/repo/of/atto
$ git pull
$ git checkout node_auth
$ go build ./cmd/atto
$ export ATTO_BASIC_AUTH_USERNAME=<your-username> ATTO_BASIC_AUTH_PASSWORD=<your-password>
$ pass nano | atto balance
```

**Comment by zQueal** [comment]
> The one thing that makes me a little hesitant is, that the authentication is not part of the official node implementation, but of a third party proxy

I think that's a reasonable precaution.

----------------------------

It works excellently. \*cheff's kiss\* 

@Gigaion mind throwing your two cents in here? I'm only able to test on windows for the next few hours.

**Comment by Gigaion** [comment]
Considering export may limit certain use cases. It'd be nice if a flag could be specified:
--atto-basic-auth=<your-username> 
--atto-basic-auth=<your-password>

Or possibly an auth file?
--atto-basic-auth-file=<path to auth file>

A good example if your using PHP to call atto, not all hosting environments will allow using export.
Here's an example: https://github.com/Gigaion/attoPHP

**Comment by codesoap** [comment]
Why do you think environment variables are limiting? Every operating system I know has them and any mature exec-library supports them. Can you give me a specific example where you are unable to use environment variables?

**Comment by zQueal** [comment]
> Why do you think environment variables are limiting?

I would argue that they're a little more secure than CLI flags. 🤷‍♂️

Either way, this functionality seems to work just fine in its current iteration.

**Comment by codesoap** [comment]
Since I have received no further objection from @Gigaion I went ahead and took the solution with the environment variables into the master branch and realesed a new version of atto.
