### ISSUE TITLE
Can't see enough decimals

### ISSUE THREAD

**Issue by negotiable-pride** [codesoap/atto#6]
I typically work with small amounts of nano, so there are a lot of 0's e.g. 0.0000283 NANO.

Your script is great but only provides up to 3 decimal points of resolution. This means sometimes my account has some nano but I don't know if it actually does AND I don't know how much there is. I just guess which is annoying.

Can you allow for an optional flag that specifies the number of decimal places to display the account balances to? 3 is a good default but it's nice to have more.

Example usage: `atto -a 4 b 10`
atto - 4th account - balance - display balance to 10 dp

**Comment by codesoap** [comment]
> One think I'm worried about is what if I have 0.00000000000000000000000001 nano left over?

What worries you about this? Are you worried that the displayed amount will always have a lot of decimal places? You could just send these tiny amounts to a "loose change" wallet, so that they don't annoy you in your daily wallet (or just burn them with `pass nano | atto s 0.00000000000000000000000001 $(atto n | atto a)`).

> Also sometimes a transaction for 0.0001 nano might become 0.000099999999999999999999 nano.

What do you mean by this? atto will never change an amount even the slightest bit. Are there other wallets which do? I think you should file a bug report, if so.
