### ISSUE TITLE
Atto Mixer

### ISSUE THREAD

**Issue by zQueal** [codesoap/atto#7]
Was thinking about NANO privacy and I think atto could really help. I'm sure you're not really interested, but I figured I'd pitch the idea regardless.

> echo $seed$ | atto mix -a 1 $amount -m $count $new_seed

Using `$seed` and using `$amount` of NANO from `-a 1` split the `$amount` into random quantities and mix them between `-m $count` addresses from the seed.

So basically;

> echo $seed | atto mix -a 1 10 -m 20 $new_seed

Would split the 10 NANO from account index 1 of $seed into random amounts (or just `$amount / $addresses`), and then shoot that balance around a bit between these 20 new addresses, and finally sweeping the total balance (10 NANO) into account index 0 of $new_seed. This way it makes it far far far more difficult to discern from where the funds initially came from. `$new_seed` could even be the same seed, mixing the balance from `-m 1` into `-m 0`.

Or something to that effect. Doesn't really have to be that complicated. I know this really goes outside of what you want atto to do, but I feel like it could really help the community and something which is requested with more and more frequency. Let me know what you think.

**Comment by codesoap** [comment]
Hi Zach,
thanks for the pitch. As you guessed, I would not include this with the "regular" atto. One could, however, write a script for this, using atto, or even a separate tool using the atto library.

I must say, though, that I'm not familiar with how mixers usually work, so I read [the Wikipedia article on it](https://en.wikipedia.org/wiki/Cryptocurrency_tumbler). There I learned, that mixers do two things:
1. They pool funds from multiple participants.
2. They mix over a random, but long period of time. This makes it harder to distinguish the transactions from normal user transactions (I assume).

2. could be achieved in a script, that is similar to what you pitched, by introducing random delays between all transactions. 1. could not be achieved with such a script; I think that's why tumblers are always external services. There is another problem with the method you suggested: The node operator could always see, that all your "mixing-transactions" come from the same IP address and thus he could easily tell what you did.

My takeaway is, that the tool you suggested could reduce traceability a little bit, but would not prevent any serious investigator from finding out where the funds came from. Thus the tool could give the user a false feeling of security, which I find very dangerous. Personally I am a "all or nothing" kind of guy, so I'm afraid I'm not interested in developing such a tool.
